Hw02 express
mstotskyi/nodejs-homework-rest-api pull request #1
Opened 2021-12-20 13:55 UTC by mstotskyi

2021-12-20 21:10 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
почему асинхронная функция?

2021-12-20 21:10 UTC, KirillKulakow commented on model/index.js
> +  console.log(contacts);
удалить

2021-12-20 21:11 UTC, KirillKulakow commented on model/index.js
> +    const updatedContact = { id: contactId, ...contacts[index], ...body };
зачем перезаписывать ид?

2021-12-20 21:11 UTC, KirillKulakow commented on model/index.js
> +    console.log(updatedContact);
удалить

2021-12-20 21:12 UTC, KirillKulakow requested changes
need some fix

2021-12-20 22:26 UTC, mstotskyi commented
виправлено згідно зауважень

2021-12-21 20:16 UTC, KirillKulakow commented on model/index.js
> +const getContactById = async contactId => {
здесь почему асинхронная функция?

2021-12-21 20:18 UTC, KirillKulakow commented on routes/api/contacts.js
> +  const contacts = await model.listContacts();
метод listContacts не асинхронный

2021-12-21 20:18 UTC, KirillKulakow commented on routes/api/contacts.js
> +  const contact = await model.getContactById(id);
метод getContactById не асинхронный

2021-12-21 20:18 UTC, KirillKulakow requested changes
Need fix

2021-12-22 19:41 UTC, KirillKulakow approved these changes

2021-12-22 21:29 UTC, merged